---
- name: Download Alloy RPM
  get_url:
    url: "{{ alloy_download_url_rpm }}"
    dest: /tmp/alloy.rpm
    mode: '0644'

- name: Install Alloy from local RPM
  ansible.builtin.package:
    name: /tmp/alloy.rpm
    state: present
    disable_gpg_check: true
  notify: restart alloy
  when: __current_deployed_version.stdout is not defined or alloy_version not in __current_deployed_version.stdout
